### ISSUE TITLE
Исправить пробелы в списке организаторов в списке мероприятий

### ISSUE THREAD

**Issue by bolanebyla** [OneIdea-IRNITU/it_academy_web#81]
![image](https://user-images.githubusercontent.com/56492378/122046880-072c2980-ce12-11eb-807a-1fc1956cd838.png)

**Comment by notTheFinal** [comment]
<img width="312" alt="Снимок экрана 2021-06-16 в 11 48 42" src="https://user-images.githubusercontent.com/49277810/122155076-cdeacc80-ce98-11eb-862e-81b173c272ca.png">
